config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  authenticate :user, -> (user) { user.supervisor? } do
    # No route 'GET /sidekiq'
    # TODO root_path unless user.admin?
    mount Sidekiq::Web => '/sidekiq'
  end
  
  devise_for :users

  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
  
  # root to: {controller:"devise/sessions", action:"new"}
  root 'facility#index'
  post '/dublicate' => 'facility#dublicating'

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:show, :edit, :update, :index]
  resources :facility, shallow: true do
    resources :kro_inspection, only: [:new, :create, :show]
    resources :examinations, concerns: [:commentable], only: [:new, :create, :show] do
      # resources :comments, only: [:create, :destroy]
    end
    resources :itineraries
    resources :employees
  end



  namespace :api do
    namespace :v1 do
      resources :users, only: [:create, :update, :show]
      resource :sessions, only: [:create]
      resource :password_restore, only: [:create]
      # resource :member do
      #   get :me, on: :collection
      #   get :index, on: :collection
      # end
    end
  end


  # root new_user_session_path #''"devise/sessions#new" #new_user_session_path#'inspection#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  belongs_to :facility
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :authenticate_user!
  before_action :facility_load, only: [:index, :new, :create, :destroy]
  before_action :itinerary_load, only: [:edit, :update, :destroy]
  
  def index
    @itineraries = @facility.itineraries
    authorize @itineraries
  end
  
  def new
    @itinerary = @facility.itineraries.new()
    authorize @itinerary, :new?
  end

  def create
    @itinerary = @facility.itineraries.new(itinerary_params)
    authorize @itinerary, :create?
    if @itinerary.save
     redirect_to facility_path(@facility), notice: "Маршрутный лист создан"
    else
      render :new#, flash[:error] = @itinerary.errors.full_messages
    end
  end

  def edit
  end

  def update
  end

  def destroy
    flash[:notice] = "Маршрутный лист удален" if @itinenrary.destroy
  end

  private

    def itinerary_load
      @itinenrary = Itinerary.find(params[:id])
      authorize @itinenrary
    end

    def facility_load
      @facility = Facility.find(params[:facility_id])
    end

    def itinerary_params
      params.require(:itinerary).permit(
 	                                      :name, 
 	                                      build_elements: [], 
 	                                      placements: [], 
 	                                      nested_placements: []
      	                               )	
    end
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/views/itineraries/index.html.haml
= link_to "Добавить маршрутных листов", [@facility, @facility.itineraries.new]
/ new_facility_itinerary_path(@facility)
%h2 Маршрутные листы
%table
 %thead
  %tr
   %th Маршрутный лист
   %th Ответственный
   %th Опции
 %tbody
  - @facility.itineraries.each do |i|
   %tr
    %td
     = i.name
    %td
     Работник
    %td
     / =# link_to "Удалить", i, method: :delete
     / =# link_to "Удалить", itinerary_path(i.id), method: :delete
     = link_to "Удалить", action: "destroy", controller: "itineraries", id: "#{i.id}", method: :delete

app/views/itineraries/new.html.haml
.new-itinenrary
 = form_for [@facility, @itinerary] do |itinerary|
  %b= @facility.name
  %hr
  = itinerary.label :name, "Название маршрутного листа"
  = itinerary.text_field :name
  %fieldset.first
   %ledend 
    %b Элемент первой вложенности
   - @facility.build_elements.each do |be|
    - unless be.placements.empty? || @facility.itineraries.map(&:build_elements).flatten.include?(be.id.to_s)
     .element-block
      .list
       .first
        = be.kind
        = itinerary.check_box("build_elements", {multiple: true}, be.id, nil)
      %br
      /----------------ПОМЕЩЕНИЯ--------------------
      %fieldset.second
       - unless be.placements.empty?
        %legend 
         %b Элементы второй вложенности
        - be.placements.includes(:nested_placements).each do |placement|
         .placement-block
          .list
           .second
            %table
             %tr
              %td
               = placement.kind
              %td
               = itinerary.check_box("placements", {multiple: true}, placement.id, nil)
           %br
           /----------------ВНУТРЕННИЕ-ПОМЕЩЕНИЯ----------       
           %fieldset.third
            - unless placement.nested_placements.empty?
             %legend
              %b Элементы третей вложенности
             - placement.nested_placements.each do |np|
              .nested-placement-block
               .list
                .third
                 = np.kind
                 = itinerary.check_box("nested_placements", {multiple: true}, np.id, nil)
                %br
  %br
  %br
  = itinerary.submit "Создать"