config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  authenticate :user, -> (user) { user.supervisor? } do
    # No route 'GET /sidekiq'
    # TODO root_path unless user.admin?
    mount Sidekiq::Web => '/sidekiq'
  end
  
  devise_for :users

  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
  
  # root to: {controller:"devise/sessions", action:"new"}
  root 'facility#index'
  post '/dublicate' => 'facility#dublicating'

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:show, :edit, :update, :index]
  resources :facility, shallow: true do
    resources :kro_inspection, only: [:new, :create, :show]
    resources :examinations, concerns: [:commentable], only: [:new, :create, :show] do
      # resources :comments, only: [:create, :destroy]
    end
    resources :itineraries
    resources :employees
  end



  namespace :api do
    namespace :v1 do
      resources :users, only: [:create, :update, :show]
      resource :sessions, only: [:create]
      resource :password_restore, only: [:create]
      # resource :member do
      #   get :me, on: :collection
      #   get :index, on: :collection
      # end
    end
  end


  # root new_user_session_path #''"devise/sessions#new" #new_user_session_path#'inspection#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :facility
  has_many :inventory
  # has_many :sectors
  # validates :name, :surname, :birthday, :sex, :document_type, :document_number, presence: true
end
# class User < ActiveRecord::Base
#   has_many :players, :class_name => "User",  :foreign_key => "coach_id"
#   belongs_to :coach, :class_name => "User"
# end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :facility_load, only: [:index, :new, :create, :destroy]
  before_action :load_employee, only: [:edit, :update, :destroy, :show]
  
  def index
    @employees = @facility.employees
    authorize @employees
  end

  def new
    @employee	= @facility.employees.new
    authorize @employee, :new?
  end

  def create
    @employee = @facility.employees.new employee_params
    authorize @employee, :create?
    if @employee.save
      redirect_to  facility_path(@facility)
    else
      # err_any?(@this_new)
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    redirect_to facility_employee_index_path(@facility) if @employee.destroy
  end

  private

    def facility_load
      @facility = Facility.find params[:facility_id]
    end

    def load_employee
      @employee = Employee.find params[:id]
      authorize @employee 
    end

    def employee_params
      params.require(:employee).permit(:name, :sex, languages: [])    
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.haml
%h2 edit employee
.employee

app/views/employees/index.html.haml
%h2 Работники
= link_to 'Создать нового работника', [@facility, @facility.employees.new]
/ new_facility_employee_path(@facility)
.employee
 - @facility.employees.each do |e|
  = e.name
  %br

app/views/employees/new.html.haml
%h2 new employee
.employee
 = form_for @this_new, url: employee_index_path, method: :post do |f|
  = f.label :name
  %br
  = f.text_field :name
  %br
  = f.label :sex
  %br
  = f.check_box :sex
  %br
  = f.label :languages, 'France language'
  %br
  = f.check_box("languages", {multiple: true}, "France", nil)
  %br
  = f.label :languages, 'Deutsch language'
  %br
  = f.check_box("languages", {multiple: true}, "Deutsch", nil)
  %br
  = f.label :languages, 'Russian language'
  %br
  = f.check_box("languages", {multiple: true}, "Russian", nil)
  %br
  = f.submit 'Создать'

  - if @this_new.errors.any?
   = @err_s = @this_new.errors.full_messages.map { |i| i }
   = flash[:errors] = @err_s.to_s[1..-2]



.employee
 = form_for [@facility, @employee] do |f|
  = f.label :name
  %br
  = f.text_field :name
  %br
  = f.submit 'Создать'

app/views/employees/show.html.haml
%h3 show employee
.employee