config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  authenticate :user, -> (user) { user.supervisor? } do
    # No route 'GET /sidekiq'
    # TODO root_path unless user.admin?
    mount Sidekiq::Web => '/sidekiq'
  end
  
  devise_for :users

  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
  
  # root to: {controller:"devise/sessions", action:"new"}
  root 'facility#index'
  post '/dublicate' => 'facility#dublicating'

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:show, :edit, :update, :index]
  resources :facility, shallow: true do
    resources :kro_inspection, only: [:new, :create, :show]
    resources :examinations, concerns: [:commentable], only: [:new, :create, :show] do
      # resources :comments, only: [:create, :destroy]
    end
    resources :itineraries
    resources :employees
  end



  namespace :api do
    namespace :v1 do
      resources :users, only: [:create, :update, :show]
      resource :sessions, only: [:create]
      resource :password_restore, only: [:create]
      # resource :member do
      #   get :me, on: :collection
      #   get :index, on: :collection
      # end
    end
  end


  # root new_user_session_path #''"devise/sessions#new" #new_user_session_path#'inspection#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/facility.rb
class Facility < ApplicationRecord
  include AbstractController::Translation

  [:documents, :build_elements, :itineraries, :employees, :inventory, :examinations, :shipments].each do |model|
    has_many model, dependent: :destroy
  end

  validates :name, presence: true
  
  accepts_nested_attributes_for :build_elements, allow_destroy: true, reject_if: :all_blank

  def last_mark
    examinations.last ? examinations.last.mark : 0
  end

  # def self.associations_list
  #   reflect_on_all_associations(:has_many).map(&:name)
  # end

  # def associations_list
  #   self.class.reflect_on_all_associations(:has_many).map(&:name)
  # end

  def amout_of_all_inspections
    examinations ? examinations.count : 0
  end

  def data_for_chart
    data = examinations.pluck(:created_at, :mark).map{|i| ["#{i.first.asctime}", i.second ]}
  end

  def dublicate(new_facility_name)
    DublicatingFacilityJob.perform_now(self.id, new_facility_name)
  end

end

app/controllers/facility_controller.rb
class FacilityController < ApplicationController
  before_action :authenticate_user!
  before_action :facility_load, only: [:show, :edit, :update, :destroy]

  def index
    @facilities = Facility.includes(:examinations)
    authorize @facilities
  end

  def new
    @facility = Facility.new
    authorize @facility
  end

  def create
    @facility = Facility.new(facility_params)
    authorize @facility
    if @facility.save
      redirect_to facility_index_path
    else
      render :new
    end
  end

  def show
    @exams = @facility.examinations.from_year
  end

  def edit
  end

  def update
    if @facility.update(facility_params)
      redirect_to @facility
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path if @facility.destroy
  end

  def dublicating
    @facility = Facility.find params[:facility]
    authorize @facility
    new_name = params[:dublicate_name]
    @facility.dublicate(new_name)
    redirect_to root_path
  end

  private

  def facility_load
    @facility = Facility.find(params[:id])
    authorize @facility
  end

  def facility_params
    params.require(:facility).permit(
                                      :name,
                                      :total_square, 
                                      build_elements_attributes: [
                                                                   :kind, 
                                                                   :id,
                                                                   :_destroy,
                                                                   placements_attributes: [
                                                                                            :name,
                                                                                            :kind,
                                                                                            :id,
                                                                                            :_destroy,
                                                                                            nested_placements_attributes: [
                                                                                                                           :name,
                                                                                                                           :kind,
                                                                                                                           :id,
                                                                                                                           :_destroy,
                                                                                                                           furniture_attributes: [
                                                                                                                                                  :material,
                                                                                                                                                  :id,
                                                                                                                                                  :_destroy,
                                                                                                                                                  :kind
                                                                                                                                                 ],
                                                                                                                            glass_attributes: [
                                                                                                                                               :kind,
                                                                                                                                               :id,
                                                                                                                                               :_destroy,
                                                                                                                                               :square
                                                                                                                                              ],
                                                                                                                            inside_objects_attributes: [
                                                                                                                                                        :kind,
                                                                                                                                                        :id,
                                                                                                                                                        :_destroy,
                                                                                                                                                        :square
                                                                                                                                                       ]
                                                                                                                          ],
                                                                                            furniture_attributes: [
                                                                                                                   :material,
                                                                                                                   :id,
                                                                                                                   :_destroy,
                                                                                                                   :kind
                                                                                                                  ],
                                                                                            glass_attributes: [
                                                                                                               :kind,
                                                                                                               :id,
                                                                                                               :_destroy,
                                                                                                               :square
                                                                                                              ],
                                                                                            inside_objects_attributes: [
                                                                                                               :kind,
                                                                                                               :id,
                                                                                                               :_destroy,
                                                                                                               :square
                                                                                                              ]
                                                                                          ]
                                                                  ]
                                      )

  end

end

app/views/facility/_build_element_fields.html.haml
.boxing.nested-fields
 %table
  %tr
   %td.order-number
    %p
   %td.input
    = f.text_field :kind, class: "input"
   %td.context-menu{oncontextmenu:"return false;"}
    %i{class: "fa fa-bars"}
    .context-menu-list
     %ul
      %li=link_to_add_association content_tag(:i, " Добавить вложенный элемент", class: 'fa fa-plus-square-o'), f, :placements, "data-association-insertion-method" => 'append', "data-association-insertion-node" => '.num-2', class:"add-field-link-be add-field-link"
      %li= link_to_remove_association content_tag(:i, " Удалить", class: 'fa fa-trash-o'), f
  / %tr
  /  Инфо: ...
 = f.fields_for :placements do |p|
  = render 'placement_fields', f: p

app/views/facility/_chartkick.html.haml
%i{class: "fa fa-caret-down"} 
 Графики
.charts
 .year
  = line_chart @exams.month_data_for_chart, min: 0, max: 100, xtitle: "Дата", ytitle: "Процент выполнения", library: {  hAxis: {format:"d MMM(HH:mm)"}, vAxis: {}}, title: "Оценка"
 .month  
  = line_chart [ { name: "Процент выполнения", data: @exams.month_data_for_chart }, { name: "Достоверность", data: @exams.realness_month_data } ], min: 0, max: 100, library: {  hAxis: {format: "MMM"}, vAxis: {}}
 / .month
 /  = line_chart @examinations.year_data_for_chart, min: 0, max: 100, xtitle: "Дата", ytitle: "Процент выполнения", library: {  hAxis: {format: "MMM"}, vAxis: {}}, title: "Оценка"

app/views/facility/_furniture_fields.html.haml
.furniture.partial.nested-fields
 %table
  %tr
   %td
    = f.text_field :kind
   %td.trash
    = link_to_remove_association content_tag(:i, "", class: 'fa fa-trash-o', id: "be"), f

app/views/facility/_inside_object_fields.html.haml
%table.inside-object
 %tr
  %td
   = f.text_field :kind
  %td.trash
   = link_to_remove_association content_tag(:i, "", class: 'fa fa-trash-o', id: "be"), f

app/views/facility/_inspections_index.html.haml
%table
 %thead
  %tr
   %th Дата
   %th Оценка
   %th Достоверность
   %th Проверил
 - @exams.last_five.each do |f|
  %tr
   %td
    %p=l f.created_at.to_datetime, format: :custom
   %td
    %p= link_to "#{f.mark.round(1)}", f
   %td
    %p= f.realness
   %td
    %p= f.user.name

app/views/facility/_nested_placement_fields.html.haml
.boxing-smallest.nested-fields
 %table
  %tr
   %td.order-number
    %p
   %td
    = f.text_field :kind, class: "input"
   %td.context-menu{oncontextmenu:"return false;"}
    %i{class: "fa fa-bars"}
    .context-menu-list.moved-menu
     %ul
      %li= link_to_add_association content_tag(:i, " Добавить элемент обстановки", class: 'fa fa-plus-square-o'), f, :inside_objects, "data-association-insertion-method" => 'append', "data-association-insertion-node" => '.num-3', class: 'add-field-link add-inside-object-button'
      %li= link_to_remove_association content_tag(:i, " Удалить", class: 'fa fa-trash-o'), f
  %tr.nested-list
   %td
   %td
    .triangle= content_tag(:i, " Вложенный список", class: 'fa fa-caret-up', id: "triangle")
    .inside-object-box.inside-object-box-3
   %td
    .triangle= content_tag(:i, "", class: 'fa fa-caret-up', id: "triangle")

app/views/facility/_placement_fields.html.haml
.boxing-smaller.nested-fields
 %table
  %tr.placement-input
   %td.order-number
    %p
    / = f.index
   %td
    = f.text_field :kind, class: "input"
   %td.context-menu{oncontextmenu:"return false;"}
    %i{class: "fa fa-bars"}
    .context-menu-list
     %ul
      %li=link_to_add_association content_tag(:i, " Добавить вложенный элемент", class: 'fa fa-plus-square-o'), f, :nested_placements, "data-association-insertion-method" => 'append', class:"add-field-link-pl add-field-link", "data-association-insertion-node" => '.num-3'
      %li= link_to_remove_association content_tag(:i, " Удалить", class: 'fa fa-trash-o'), f
      %li= link_to_add_association content_tag(:i, " Добавить элемент обстановки", class: 'fa fa-plus-square-o'), f, :inside_objects, "data-association-insertion-method" => 'append', "data-association-insertion-node" => '.num-2 .inside-object-box-2', class: 'add-field-link add-inside-object-button'
  %tr.nested-list
   %td
   %td
    .triangle= content_tag(:i, " Вложенный список", class: 'fa fa-caret-up', id: "triangle")
    .inside-object-box.inside-object-box-2
   %td
    / .triangle= content_tag(:i, "", class: 'fa fa-caret-down', id: "triangle")

app/views/facility/_schedule_table.html.haml
%table.table-minimal
 %thead
  %tr
   %th Время
   %th Номер ворот
   %th Номер карты
   %th in/out
 %tbody
 - TimeSheet.all.each do |d|
  %tr
   %td= l d.timestamp
   %td= d.gate_id
   %td= d.card_id
   %td= d.kind_of_enterence

app/views/facility/_stats.html.haml
.to_center
 %ul
  %li
   = @exams.last_mark
   %span Последний бал
  %li
   = @exams.from_month.count
   %span Проверок за месяц
  %li
   = @facility.amout_of_all_inspections
   %span Всего проверок

app/views/facility/edit.html.haml
.columned-forms
 = form_for @facility do |f|
  .facility-name
   %i{class: 'fa fa-pencil-square-o'}= f.text_field :name, default: 'Название нового объекта'
  .form-button
   .add-button
    = link_to_add_association content_tag(:i, " Добавить Элемент", class: 'fa fa-plus-square-o'), f, :build_elements, id: "add-be", "data-association-insertion-method" => 'append', "data-association-insertion-node" => '.num-1'
   .form-cell
    .form-column.num-1
     - build_elements = 0
     = f.fields_for :build_elements do |be|
      .boxing.nested-fields{id: be.object.id}
       - build_elements += 1
       %table
        %tr
         %td.order-number
          %p= build_elements
         %td.input
          = be.text_field :kind
         %td.context-menu{oncontextmenu:"return false;"}
          %i{class: "fa fa-bars"}
          .context-menu-list
           %ul
            %li=link_to_add_association content_tag(:i, " Добавить вложенный элемент", class: 'fa fa-plus-square-o'), be, :placements, "data-association-insertion-method" => 'append', "data-association-insertion-node" => '.num-2', class:"add-field-link-be add-field-link"
            %li= link_to_remove_association content_tag(:i, " Удалить", class: 'fa fa-trash-o'), be
    .form-column.num-2
     - build_elements = placements = 0
     = f.fields_for :build_elements do |be|
      - build_elements += 1
      = be.fields_for :placements do |pl|
       - placements += 1
       .boxing-smaller.nested-fields{id: pl.object.id, 'data-parent-id': be.object.id}
        %table
         %tr
          %td.order-number
           %p="#{build_elements}.#{placements}"
          %td.input
           = pl.text_field :kind  
          %td.context-menu{oncontextmenu:"return false;"}
           %i{class: "fa fa-bars"}
           .context-menu-list
            %ul
             %li=link_to_add_association content_tag(:i, " Добавить вложенный элемент", class: 'fa fa-plus-square-o'), pl, :nested_placements, "data-association-insertion-method" => 'append', "data-association-insertion-node" => '.num-3', class:"add-field-link-pl add-field-link"
             %li= link_to_remove_association content_tag(:i, " Удалить", class: 'fa fa-trash-o'), pl, wrapper_class: "boxing-smaller"
             %li= link_to_add_association content_tag(:i, " Добавить элемент обстановки", class: 'fa fa-plus-square-o'), pl, :inside_objects, "data-association-insertion-method" => 'append', "data-association-insertion-node" => ".num-2 ##{pl.object.id} .inside-object-box-2", class: 'add-field-link add-inside-object-button'
         %tr.nested-list.nested-fields{style: "#{pl.object.inside_objects.count == 0 ? 'display: none;' : 'display: table-row;' }"}
          %td
          %td
           .triangle= content_tag(:i, " Вложенный список", class: 'fa fa-caret-down', id: "triangle")
           .inside-object-box-2.inside-object-box
            = pl.fields_for :inside_objects do |fpl|
             %table.inside-object
              %tr
               %td
                = fpl.text_field :kind
               %td.trash
                = link_to_remove_association content_tag(:i, "", class: 'fa fa-trash-o'), fpl, wrapper_class: "inside-object"

          %td
      - placements = 0
     - build_elements = 0
    .form-column.num-3     
     - build_elements = placements = nested_placements = 0
     = f.fields_for :build_elements do |be|
      - build_elements += 1
      = be.fields_for :placements do |pl|
       - placements += 1
       = pl.fields_for :nested_placements do |npl|
        - nested_placements += 1
        .boxing-smallest.nested-fields{id: npl.object.id, 'data-parent-id': pl.object.id}
         %table
          %tr
           %td.order-number
            %p="#{build_elements}.#{placements}.#{nested_placements}"
           %td.input
            = npl.text_field :kind
           %td.context-menu.moved-menu{oncontextmenu:"return false;"}
            %i{class: "fa fa-bars"}
            .context-menu-list.moved-menu
             %ul
              %li= link_to_add_association content_tag(:i, " Добавить элемент обстановки", class: 'fa fa-plus-square-o'), npl, :inside_objects, "data-association-insertion-method" => 'append', "data-association-insertion-node" => ".num-3 ##{npl.object.id} .inside-object-box-3", class: 'add-field-link add-inside-object-button'
              %li= link_to_remove_association content_tag(:i, " Удалить", class: 'fa fa-trash-o'), npl
          %tr.nested-list{style: "#{npl.object.inside_objects.count == 0 ? 'display: none;' : 'display: table-row;' }"}
           %td
           %td
            .triangle= content_tag(:i, " Вложенный список", class: 'fa fa-caret-down', id: "triangle")
            .inside-object-box.inside-object-box-3
             = npl.fields_for :inside_objects do |fnpl|
              %table.inside-object
               %tr
                %td
                 = fnpl.text_field :kind
                %td.trash
                 = link_to_remove_association content_tag(:i, "", class: 'fa fa-trash-o'), fnpl, wrapper_class: "inside-object"
           %td
       - nested_placements = 0
      - placements = 0
     - build_elements = 0    
  .submit-button
   = f.submit "Сохранить изменения", id: "submit"
= link_to 'Удалить объект', @facility, method: :delete

app/views/facility/index.html.haml
.facility_box
 .facility
  %table
   %thead
    %tr
     %th Список Объектов
     %th Дата последней проверки
   %tbody
   - @facilities.each do |f|
    %tr
     %td= link_to f.name, facility_path(f)
     / OPTIMIZE
     /%td= f.examinations.empty? ? 'none' : localize(f.examinations.last.created_at)
     %td= f.examinations.empty? ? 'none' : f.examinations.last.created_at.to_formatted_s(:custom)
= link_to 'Создать новый объект', new_facility_path

app/views/facility/new.html.haml
.columned-forms
 = form_for @facility, url: facility_index_path, method: :post do |f|
  = f.label :name, 'Название нового объекта'
  = f.text_field :name, default: 'Название нового объекта'
  .form-button
   .add-button
    = link_to_add_association content_tag(:i, " Добавить Элемент", class: 'fa fa-plus-square-o'), f, :build_elements, id: "add-be", "data-association-insertion-method" => 'append', "data-association-insertion-node" => '.num-1'
   .form-cell
    .form-column.num-1
     = f.fields_for :build_elements do |be|
      = render partial: 'build_element_fields', f: be
    .form-column.num-2
    .form-column.num-3
  .submit-button
   = f.submit "Создать", id: "submit"
= render 'layouts/dublicating_facility'

app/views/facility/show.html.haml
.facility_box
 .name
  %h1= @facility.name
  = link_to 'Редактировать объект', edit_facility_path(@facility), class: 'facility-edit-link'
  %br
  = link_to 'Начать проверку', new_facility_examination_path(@facility)
  %br
 .stats
  = render partial: 'stats'
 .inspection_list
  = render partial: 'inspections_index'
 .chartkick
  = render partial: 'chartkick'
 / .itinerary-index
 /  = render template: 'itineraries/index'
 


 / .emplyee-index
 /  = render template: 'employees/index'
/ .schedule_table
/ =# render partial: 'schedule_table'