config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  authenticate :user, -> (user) { user.supervisor? } do
    # No route 'GET /sidekiq'
    # TODO root_path unless user.admin?
    mount Sidekiq::Web => '/sidekiq'
  end
  
  devise_for :users

  
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end
  
  # root to: {controller:"devise/sessions", action:"new"}
  root 'facility#index'
  post '/dublicate' => 'facility#dublicating'

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:show, :edit, :update, :index]
  resources :facility, shallow: true do
    resources :kro_inspection, only: [:new, :create, :show]
    resources :examinations, concerns: [:commentable], only: [:new, :create, :show] do
      # resources :comments, only: [:create, :destroy]
    end
    resources :itineraries
    resources :employees
  end



  namespace :api do
    namespace :v1 do
      resources :users, only: [:create, :update, :show]
      resource :sessions, only: [:create]
      resource :password_restore, only: [:create]
      # resource :member do
      #   get :me, on: :collection
      #   get :index, on: :collection
      # end
    end
  end


  # root new_user_session_path #''"devise/sessions#new" #new_user_session_path#'inspection#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_dublicating_facility.html.haml
.or-copy-object
 %h2 или создать дубликат объекта:
 = form_tag '/dublicate', method: :post do
  = select_tag "facility", options_from_collection_for_select(Facility.all, "id", "name"), { defailt: "hi" }
  = text_field_tag "dublicate_name", "Название дубликата"
  = submit_tag "ok"
 %br

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KroApp2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//www.google.com/jsapi" %> <!-- To Add -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= evil_icons_sprite %>
    <%#console%>
  </head>
  <body>
  <div class="notice"></div>
  <div class="error"></div>
    <header class="centered-navigation" role="banner">
      <div class="centered-navigation-wrapper">
        <nav role="navigation">
        <% if signed_in? %>
          <ul id="js-centered-navigation-menu" class="centered-navigation-menu show">
            <li id="js-centered-more" class="nav-link"><%= link_to 'Объекты', facility_index_path%>
            </li>
            <li  class="nav-link"><%= link_to 'Пользователи', users_path if current_user.supervisor %>
            <li  class="nav-link"><%= link_to 'Личный кабинет', user_path(current_user) %>
            <!-- <li  class="nav-link"><%= link_to 'Рабочий персонал', users_path if current_user.supervisor %> -->
            <!-- <li  class="nav-link"><%= link_to 'Складские передвижения', users_path if current_user.supervisor %> -->
          </ul>
          <%end%>
        </nav>
      </div>
    </header>
      
    <%#= localize(Time.now) %>
    <%= yield %>
  </body>
  <!-- <footer class="footer" role="contentinfo"></footer> -->
</html>